### PR TITLE
App icon refresh

### PR DESCRIPTION
**Pull request by JSEHV**
App icon refresh

### CODE REVIEW

**Comment by Tomin1** [comment]
I have had thoughts of simplifying the current icon as it's way too heavy on details that will not show up even in 256×256 icons (which is larger than what's needed). The design ideas behind the current icon are:
- It must show that this is a card game, thus there is that ace of spades there representing playing cards
- As the name of the application has word 'deck' in it, there is also a deck of cards (could be a deck of a ship too if can be nicely included without compromising the other design ideas or the visual look of the icon)
- The background color is taken from the color of the tableau in the app
- I just really like the teardrop shape and it fitted the icon well IMO, so I wanted to use that

This design ticks only one of these boxes so it's not quite what I'm looking for as the icon of Patience Deck. If you want to contribute an icon, would you be willing to make some significant alterations to your design? I'm not saying that it has to be like described above but as it is I don't think this icon is a better fit for Patience Deck than the current icon.

Also something else I noticed is that you put those 'A's to the other side on the cards than what I'm used to and what's used in Patience Deck (for a good reason: cards extend to right and down so the rank of the card is always visible). However I can see why you have decided otherwise here, but perhaps the lower card could be tilted to the other side as is usual with playing cards. When it comes to color, I would likely accept a gradient background but only if it's subtle and the outline of the icon would be still in that same green color. Perhaps game over overlay's (Game over / You win screen with two buttons) gradient from white to transparent could be used, if it otherwise fits the icon of course. Outline should be the same size as it is in Sailfish icons in general.

Then some technical notes: The icon file should be `patience-deck.svg` and that's the only icon file that should be shipped with the sources. Now you have file named `harbour-patience-deck.svg` and you also included `png` files generated from that. I'm generating the pngs while building the package so I don't have to ship binary files with the sources and changes to the source file will always show up in the final result.

For commit message please add Signed-off-by line with (for example) `git commit --amend --signoff` [to confirm that you have rights to the contribution and it can be included in the larger work](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for). Also mention how the icon is licensed so it's easy to confirm by anyone trying to look it up. I very much prefer GPLv3 (with exact version) but I can consider others (like creative commons license) too. A simple sentence stating it in commit message will do. Without a license I simply can't include any new files from contributors.

**Comment by JSEHV** [comment]
I hope this icon version (commit 59029fe) suits you better.

**Comment by Tomin1** [comment]
> I hope this icon version (commit [59029fe](https://github.com/Tomin1/patience-deck/commit/59029fe2f5ebb3e8403a42f115856d574cccdda5)) suits you better.

Hi! Thanks!

First of all, my apologies that I haven't replied any sooner. I've been busy most of the summer and now I finally had some time to consider this new version. It does look better than the previous version. I checked how it looks in icon sizes (86x86 - 172x172) and tried editing it a bit. I'm thinking we should still keep that teardrop shape the current icon has and make the new version a bit more 3D-like by changing the deck of cards a bit. My playing around with transformations in Inkscape resulted in this:


I think you could probably make a more polished version if you are still interested in contributing. At least that deck of cards looks a bit flat now and some artistic eye wouldn't hurt there. Additionally I rotated that ace of spades there because thought it might look a little more interesting if the cards weren't in a grid but I'm not sure if its really better like that.

**Comment by Tomin1** [comment]
I think I'll stick to the current icon for now. I recently made some improvements to it and the style matches the cards so in my opinion it's good enough. That said, the current version could probably use some further refinements but they can wait. I'm closing this PR but I'm open to discuss the icon if there is will to do improvements still.

**Pull request closed without merging**
